services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpassword
    networks:
      - my_network

  flask-app:
    build:
      context: ./custom-dashboard  # Points to the Flask app's Dockerfile location
    container_name: flask-app
    ports:
      - "5000:5000"  # Exposes Flask on port 5000
    environment:
    - FLASK_ENV=development
    - FLASK_DEBUG=1
    - MQTT_BROKER=mosquitto
    - RASP_BROKER=192.168.0.100
    - blade_1=60
    - blade_2=60
    - blade_3=60
    volumes:
      - ./custom-dashboard:/app
    networks:
      - my_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    networks:
      - my_network
    ports:
      - "1883:1883"  # Exposes MQTT broker to localhost and containers
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  mqtt-prediction:
    build:
      context: ./mqtt-prediction
    container_name: mqtt-prediction
    volumes:
      - ./mqtt-prediction:/app
    networks:
      - my_network
    environment:
      - MQTT_BROKER=mosquitto  # Pointing to the Mosquitto container
      - RASP_BROKER=192.168.0.100
      - MQTT_PORT=1883
      - PUBLISH_TOPIC=wind_turbine/predictions
      - PUBLISH_INTERVAL=5
      - blade_1=60
      - blade_2=60
      - blade_3=60
networks:
  my_network:
    name: docker_my_network
    driver: bridge

