services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpassword
    networks:
      - my_network

  flask-app:
    build:
      context: ./custom-dashboard  # Points to the Flask app's Dockerfile location
    container_name: flask-app
    ports:
      - "5000:5000"  # Exposes Flask on port 5000
    environment:
    - FLASK_ENV=development
    - FLASK_DEBUG=1
    volumes:
      - ./custom-dashboard:/app
    networks:
      - my_network
  mqtt-prediction:
    build:
      context: ./mqtt-prediction
    container_name: mqtt-prediction
    volumes:
      - ./mqtt-prediction:/app
    networks:
      - my_network
    environment:
      - MQTT_BROKER=host.docker.internal
      - MQTT_PORT=1883
      - MODEL_FILENAME=wind_turbine_model.pkl
networks:
  my_network:
    driver: bridge

