services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    environment:
      - TZ=America/New_York
    networks:
      - my_network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpassword
    networks:
      - my_network

  flask-app:
    build:
      context: ./custom-dashboard  # Points to the Flask app's Dockerfile location
    container_name: flask-app
    ports:
      - "5000:5000"  # Exposes Flask on port 5000
    environment:
    - FLASK_ENV=development
    - FLASK_DEBUG=1
    volumes:
      - ./custom-dashboard:/app
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

