services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Exposes Grafana on port 3000
    volumes:
      - ./grafana-data:/var/lib/grafana  # Bind mount host directory to persist Grafana data
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword  # Set your admin password here

  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"  # Exposes Node-RED on port 1880
    volumes:
      - ./node-red-data:/data  # Bind mount host directory to persist Node-RED data
    environment:
      - TZ=America/New_York  # Set your timezone here

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"  # Exposes InfluxDB on port 8086
    volumes:
      - ./influxdb-data:/var/lib/influxdb  # Bind mount host directory to persist InfluxDB data
    environment:
      - INFLUXDB_DB=mydb  # Creates a default database 'mydb'
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpassword
      

# No volumes section is needed as we are using bind mounts
